
#### general settings

name: 01_IRN-CRM_DB_x2_q90_scratch_DIV2K
use_tb_logger: true
model: IRN-CRM
distortion: sr
scale: 2
gpu_ids: [0]


#### datasets

datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: ~ # path to training HR images
    dataroot_LQ: ~ # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: ~ # path to validation HR images
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8]
  scale: 2
  init: xavier

network_R:
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 8
  gc: 32


#### path

path:
  pretrain_model_G: ../experiments/pretrained_models/IRN_x2_finetune.pth
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 2e-4
  lr_R: !!float 2e-4
  beta1: 0.9
  beta1_R: 0.9
  beta2: 0.999
  beta2_R: 0.999
  niter: 50000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [10000, 20000, 30000, 40000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1
  pixel_criterion_jpeg: l2

  manual_seed: 10

  val_freq: !!float 5e3

  lambda_fit_forw: 4.
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10

  jpg_quality: 90
  lambda_rec_jpeg: 1
  lambda_joint_back: 0
  only_jpeg_reconstruction: True
  add_joint_loss: False

test:
  jpg_quality: 90


#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
